-- Canadian Airports
INSERT INTO Airports VALUES ('YWH', 'Victoria', 'Canada', '-08:00');
INSERT INTO Airports VALUES ('YYJ', 'Victoria', 'Canada', '-08:00');
INSERT INTO Airports VALUES ('YVR', 'Vancouver', 'Canada', '-08:00');
INSERT INTO Airports VALUES ('YKA', 'Kamloops', 'Canada', '-08:00');
INSERT INTO Airports VALUES ('YXT', 'Terrace', 'Canada', '-08:00');
INSERT INTO Airports VALUES ('YLW', 'Kelowna', 'Canada', '-08:00');
INSERT INTO Airports VALUES ('YYC', 'Calgary', 'Canada', '-07:00');
INSERT INTO Airports VALUES ('YEG', 'Edmonton', 'Canada', '-07:00');
INSERT INTO Airports VALUES ('YQR', 'Regina', 'Canada', '-06:00');
INSERT INTO Airports VALUES ('YXE', 'Saskatoon', 'Canada', '-06:00');
INSERT INTO Airports VALUES ('YWG', 'Winnipeg', 'Canada', '-06:00');
INSERT INTO Airports VALUES ('YQT', 'Thunder Bay', 'Canada', '-05:00');
INSERT INTO Airports VALUES ('YYZ', 'Toronto', 'Canada', '-05:00');
INSERT INTO Airports VALUES ('YOW', 'Ottawa', 'Canada', '-05:00');
INSERT INTO Airports VALUES ('YUL', 'Montreal', 'Canada', '-05:00');
INSERT INTO Airports VALUES ('YQB', 'Quebec City', 'Canada', '-05:00');
INSERT INTO Airports VALUES ('YFC', 'Fredericton', 'Canada', '-04:00');
INSERT INTO Airports VALUES ('YQM', 'Moncton', 'Canada', '-04:00');
INSERT INTO Airports VALUES ('YYG', 'Charlottetown', 'Canada', '-04:00');
INSERT INTO Airports VALUES ('YHZ', 'Halifax', 'Canada', '-04:00');
INSERT INTO Airports VALUES ('YYT', 'St. John''s', 'Canada', '-03:30');
-- American Airports
INSERT INTO Airports VALUES ('HNL', 'Honolulu', 'USA', '-10:00');
INSERT INTO Airports VALUES ('ANC', 'Anchorage', 'USA', '-09:00');
INSERT INTO Airports VALUES ('SEA', 'Seattle-Tacoma', 'USA', '-08:00');
INSERT INTO Airports VALUES ('PDX', 'Portland', 'USA', '-08:00');
INSERT INTO Airports VALUES ('SFO', 'San Francisco', 'USA', '-08:00');
INSERT INTO Airports VALUES ('LAX', 'Los Angeles', 'USA', '-08:00');
INSERT INTO Airports VALUES ('DEN', 'Denver', 'USA', '-07:00');
INSERT INTO Airports VALUES ('SLC', 'Salt Lake City', 'USA', '-07:00');
INSERT INTO Airports VALUES ('ABQ', 'Albuquerque', 'USA', '-07:00');
INSERT INTO Airports VALUES ('LAS', 'Las Vegas', 'USA', '-07:00');
INSERT INTO Airports VALUES ('PHX', 'Phoenix', 'USA', '-07:00');
INSERT INTO Airports VALUES ('IAH', 'Huston', 'USA', '-06:00');
INSERT INTO Airports Values ('DFW', 'Dallas/Fort Worth', 'USA', '-06:00');
INSERT INTO Airports VALUES ('MSP', 'Minneapolis-Saint Paul', 'USA', '-06:00');
INSERT INTO Airports VALUES ('STL', 'Saint Louis', 'USA', '-06:00');
INSERT INTO Airports VALUES ('MEM', 'Memphis', 'USA', '-06:00');
INSERT INTO Airports VALUES ('ORD', 'Chicago', 'USA', '-06:00');
INSERT INTO Airports VALUES ('DTW', 'Detroit', 'USA', '-05:00');
INSERT INTO Airports VALUES ('CLE', 'Cleveland', 'USA', '-05:00');
INSERT INTO Airports VALUES ('CVG', 'Cincinnati', 'USA', '-05:00');
INSERT INTO Airports VALUES ('PHL', 'Philadelphia', 'USA', '-05:00');
INSERT INTO Airports VALUES ('JFK', 'New York', 'USA', '-05:00');
INSERT INTO Airports VALUES ('LGA', 'New York', 'USA', '-05:00');
INSERT INTO Airports VALUES ('EWR', 'Newark', 'USA', '-05:00');
INSERT INTO Airports VALUES ('IAD', 'Washington', 'USA', '-05:00');
INSERT INTO Airports VALUES ('BWI', 'Baltimore/Washington', 'USA', '-05:00');
INSERT INTO Airports VALUES ('BOS', 'Boston', 'USA', '-05:00');
INSERT INTO Airports VALUES ('CLT', 'Charlotte/Douglas', 'USA', '-05:00');
INSERT INTO Airports VALUES ('ATL', 'Atlanta', 'USA', '-05:00');
INSERT INTO Airports VALUES ('FLL', 'Fort Lauderdale', 'USA', '-05:00');
INSERT INTO Airports VALUES ('MCO', 'Orlando', 'USA', '-05:00');
INSERT INTO Airports VALUES ('MIA', 'Miami', 'USA', '-05:00');
-- Mexico
INSERT INTO Airports VALUES ('MEX', 'Mexico City', 'Mexico', '-06:00');
-- South America
INSERT INTO Airports VALUES ('LIM', 'Lima', 'Peru', '-05:00');
INSERT INTO Airports VALUES ('SCL', 'Santiago', 'Chile', '-04:00');
INSERT INTO Airports VALUES ('GRU', 'Sao Paulo', 'Brazil', '-03:00');
INSERT INTO Airports VALUES ('EZE', 'Buenos Aires', 'Argentina', '-03:00');
-- Europe
INSERT INTO Airports VALUES ('DUB', 'Dublin', 'United Kingdom', '+00:00');
INSERT INTO Airports VALUES ('LHR', 'London Heathrow', 'United Kingdom', '+00:00');
INSERT INTO Airports VALUES ('LGW', 'London Gatwick', 'United Kingdom', '+00:00');
INSERT INTO Airports VALUES ('STN', 'London Stansted', 'United Kingdom', '+00:00');
INSERT INTO Airports VALUES ('MAN', 'Manchester', 'United Kingdom', '+00:00');
INSERT INTO Airports VALUES ('CDG', 'Paris', 'France', '+01:00');
INSERT INTO Airports VALUES ('ORY', 'Paris', 'France', '+01:00');
INSERT INTO Airports VALUES ('AMS', 'Amsterdam', 'Holland', '+01:00');
INSERT INTO Airports VALUES ('FRA', 'Frankfurt', 'Germany', '+01:00');
INSERT INTO Airports VALUES ('MAD', 'Madrid', 'Spain', '+01:00');
INSERT INTO Airports VALUES ('BCN', 'Barcelona', 'Spain', '+01:00');
INSERT INTO Airports VALUES ('PMI', 'Palma', 'Spain', '+01:00');
INSERT INTO Airports VALUES ('MUC', 'Munich', 'Germany', '+01:00');
INSERT INTO Airports VALUES ('ZRH', 'Zurich', 'Switzerland', '+01:00');
INSERT INTO Airports VALUES ('VIE', 'Vienna', 'Austria', '+01:00');
INSERT INTO Airports VALUES ('FCO', 'Rome', 'Italy', '+01:00');
INSERT INTO Airports VALUES ('MXP', 'Lombardy', 'Italy', '+01:00');
INSERT INTO Airports VALUES ('CPH', 'Copenhagen', 'Denmark', '+01:00');
INSERT INTO Airports VALUES ('BRU', 'Brussels', 'Belgium', '+01:00');
-- Africa
INSERT INTO Airports VALUES ('CAI', 'Cairo', 'Egypt', '+02:00');
INSERT INTO Airports VALUES ('CPT', 'Cape Town', 'South Afria', '+02:00');
INSERT INTO Airports VALUES ('JNB', 'Johannesburg', 'South Afria', '+02:00');
INSERT INTO Airports VALUES ('NBO', 'Nairobi', 'Kenya', '+03:00');
-- Middle East
INSERT INTO Airports VALUES ('IST', 'Istanbul', 'Turkey', '+02:00');
INSERT INTO Airports VALUES ('AYT', 'Antalya', 'Turkey', '+02:00');
INSERT INTO Airports VALUES ('DXB', 'Dubai', 'UAE', '+04:00');
-- Asia
INSERT INTO Airports VALUES ('NRT', 'Narita', 'Japan', '+09:00');
INSERT INTO Airports VALUES ('HND', 'Tokyo', 'Japan', '+09:00');
INSERT INTO Airports VALUES ('ICN', 'Seoul', 'Korea', '+09:00');
INSERT INTO Airports VALUES ('GMP', 'Seoul', 'Korea', '+09:00');
INSERT INTO Airports VALUES ('HKG', 'Hong Kong', 'China', '+08:00');
INSERT INTO Airports VALUES ('PEK', 'Beijing', 'China', '+08:00');
INSERT INTO Airports VALUES ('PVG', 'Shanghai', 'China', '+08:00');
INSERT INTO Airports VALUES ('CAN', 'Guangzhou', 'China', '+08:00');
INSERT INTO Airports VALUES ('TPE', 'Taoyuan', 'China', '+08:00');
INSERT INTO Airports VALUES ('SZX', 'Shenzhen', 'China', '+08:00');
INSERT INTO Airports VALUES ('KUL', 'Kual Lumpur', 'Malaysia', '+08:00');
INSERT INTO Airports VALUES ('SIN', 'Changi', 'Singapore', '+08:00');
INSERT INTO Airports VALUES ('BKK', 'Bang Phli', 'Thailand', '+07:00');
INSERT INTO Airports VALUES ('DMK', 'Bangkok', 'Thailand', '+07:00');
INSERT INTO Airports VALUES ('CGK', 'Jakarta', 'Indonesia', '+07:00');
INSERT INTO Airports VALUES ('DEL', 'Delhi', 'India', '+05:30');
INSERT INTO Airports VALUES ('BOM', 'Mumbai', 'India', '+05:30');
-- Australia
INSERT INTO Airports VALUES ('SYD', 'Sydney', 'Australia', '+10:00');
INSERT INTO Airports VALUES ('MEL', 'Melbourne', 'Australia', '+10:00');

