INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Barnett'), 1.2);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Bigboote'), 0.9);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Camp'), 2.3);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Careful Walker'), 1.8);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Chief Crier'), 0.5);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Fish'), 3.1);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Kim Chi'), 2.4);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Littlejohn'), 1.7);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Rajeesh'), 1.3);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Smallberries'), 4.2);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Whorfin'), 4.4);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Yaya'), 1.6);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Emdell'), 3.5);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Parker'), 2.9);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Lithgow'), 2.1);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Barnett'), 1.9);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Camp'), 2.31);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Chief Crier'), 4.3);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Kim Chi'), 3.6);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Rajeesh'), 2.1);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Camp'), 0.9);
INSERT INTO Baggage VALUES(BaggageIds.nextval, (SELECT id FROM Passengers WHERE firstName='John' AND lastName='Rajeesh'), 1.8);
